### ISSUE TITLE
[Solved] Default config fails with: 'mozilla/central' is not a commit and a branch 'master' cannot be created from it

### ISSUE THREAD

**Issue by oslego** [sole/cinnabarify#11]
I tried running the default config and it crashed after a very lengthy download:

```
From hg::https://hg.mozilla.org/mozilla-unified
 * [new branch]                bookmarks/central -> mozilla/bookmarks/central
fatal: 'mozilla/central' is not a commit and a branch 'master' cannot be created from it
```

To fix this, I switched to the destination folder and ran:
```
git checkout --track -b master mozilla/bookmarks/central
```
instead of the following found in [`main.sh`](https://github.com/sole/cinnabarify/blob/master/main.sh#L60):
```
git checkout --track -b master mozilla/central
```

This seems to have fixed the issue, though I'm not sure why. Perhaps the [` -t bookmarks/central`](https://github.com/sole/cinnabarify/blob/master/main.sh#L40) from `main.sh` was ignored on my system (Mac OS Sierra 10.12.6 /  git 2.13.1).

Putting this here in case it helps someone else.

@sole I'm not sure if the config needs to be updated or not. I don't fully understand how it all works.

**Comment by sole** [comment]
I messed up and did the same fix you did but I did not update the script, my bad! I'm fixing it now and should not happen again (fingers crossed)
